### PR TITLE
[TEST][CHORE]  Convert existing browser dependent tests to browserless integrationtests

### PR DESCRIPTION
**Pull request by TimSusa**
- Test for adding virtual midi out / in established
- All test for "webmidi, inputs, outputs, platform" were converted
- A nyc code-coverage was established, reporting to cli
- Shutting tests gracefully down by --exit option
- Test-files given .test.js postfix given
- A couple of pending tests were fixed, which brought the test-suite to crash sometimes, by adding  missing done() callback
- A basic circleci configuration was added, to prepare automated linting and testing
- Chapter Testing was added to the README.md
- Rebase from master to get rid of conflicts

### CODE REVIEW

**Comment by djipco** [comment]
Thanks. This is awesome! 

I'm currently looking through everything and there are things I'm not sure about...

* I haven't used continuous integration. Should `.circleci` be in `.gitignore` ?
* I usually ignore `.vscode` but I see that `launch.json` is being tracked. Is this necessary? (I do not use VS Code). 
* I will reword `README.md` a little bit.

**Comment by djipco** [comment]
I created a `CONTRIBUTING.md` file and moved the **Testing** section to it. Since this is information meant for developers, it seemed appropriate. The `CONTRIBUTING.md` file is now referenced in `README.md`.

**Comment by djipco** [comment]
JavaScript files in the `/test` folder should probably obey `eslintrc.js` settings (quotes, no-unused-var, etc.) if we want to keep the codebase clean. 

When I run **eslint** against that folder, I get a ton of errors. They are mostly related to using single quotes instead of double quotes. Do you think you can fix those?

Once this is done, I will change the script in `package.json` to:

```javascript
"lint": "eslint ./src/*.js ./test/*.js"
```

**Comment by TimSusa** [comment]
I would handle test code little diffrerent to production code, because why not use here modern es6? Otherwise did you already try eslint ./ --fix, which would fix simple issues globally?

Furthermore, launch.json contains a debugging configuration, where time was invested to get this established. Maybe this could be useful for the project? Same with circle-ci. Of course you can do with that what you want.

CONTRIBUTING.md is fantastic! Thanks for using my PR. It makes me happy if I could help you!

**Comment by djipco** [comment]
By tweaking the `.eslintrc.js` file and fixing the `*.test.js` files I was able to get almost all the way there. Now, the only errors thrown by eslint are:

```
error  'jz' is assigned a value but never used  no-unused-vars
```

I do not know why. Ideas?

Regarding, `.circleci` and `.vscode`, I'll leave them alone. I will simply ignore them in my own editor.

**Comment by djipco** [comment]
@TimSusa I just realized something. The `/test/index.html` page can no longer be used to easily test the code against a specific browser. If browsers differ in their implementation, we will not know.

While the automation is great, the test suite only tests against Jazz-Soft's implementation of the Web MIDI API which could be faulty or differ from the ones in Chrome or the upcoming Firefox implementation.

**Comment by TimSusa** [comment]
Obviously this is the price you pay, to get tests independent on browser environments. I would claim this is a good step forward as you might have seen, that webmidi seems to work on nodejs. Of course I can understand your concerns and of course it makes sense to safe your work. This first thing that popped into my mind is simply setting an ENV like "BROWSER=NONE" to signalise the test code, that we are in the one world, or in the other. The ENV can be injected in the package.json script. As a first step one could switch in the code that is needed.

**Comment by djipco** [comment]
Your PR is generating a bunch of conflicts that are not real ones. It seems mostly related to the way the  content of the files is ordered. Can you check it out?

**Comment by TimSusa** [comment]
I hope everything is fine with: https://github.com/djipco/webmidi/pulls

**Comment by djipco** [comment]
Everything has now been merged in. Cheers!

**Pull request merged**
