### PR TITLE
add nprn receive listener

### PR DESCRIPTION
**Pull request by misterinterrupt**
Hey Webmidi crew! Thanks for all your work on this library so far.
I have seen a few issues where people mentioned receiving NRPN messages and I also wanted this feature to be in the WebMidi library for my own use. 

If it is something that you would like to include, please let me know if there are any changes that can help it be consistent with the current code. I am able to test it with my Akai MPD218, which does the incremental NRPNs and its working on knobs across multiple channels.

### CODE REVIEW

**Comment by djipco** [comment]
@misterinterrupt Thanks for your awesome work on this! I have been meaning to look into NRPNs for a while but never got around to it.

I do have 2 comments, though (bear in in mind that I haven't used NRPNs that much and only started looking at the technical implementation when I saw your PR): 

- Maybe I'm missing something but I do not see a reason to explicitely enable NRPNs via the 3rd parameter of the `enable()` function. Couldn't we just dispatch an event when a valid NRPN sequence is detected? It would just be an additional event on top of the individual CC events.

- If there ever was a need (performance?) to disable the dispatching of NRPN events, I would prefer for it to be dynamic via a setter (i.e. `dispatcheNrpn = true` or `dispatcheNrpn = false`). To keep things simple, I would enable it by default.

Thoughts?

**Comment by misterinterrupt** [comment]
Hey very cool! 
This is all awesome feedback. I agree with you about all of these things, so I will do these things and update the PR
1. Enable it by default
2. have a dispatchNRPN setter for optionally disabling the events 
3. make the cc's all pass through regardless of the NRPN sequences
4. change it to the three event types 
5. modify the readme example and any code comments to reflect these changes

**Comment by misterinterrupt** [comment]
oh one other thing.. I haven't looked at this yet in code, but I'd like to try to get the nrpn events to show up in the catch-all callback.
I know I have seen devs use webmidi but not take advantage of the different event listeners. I think adding the nrpns there would be convenient if its possible.

**Comment by djipco** [comment]
> I would prefer for it to be dynamic via a setter (i.e. `dispatchNrpn = true` or `dispatchNrpn = false`).

In retrospect, I think we should use a setter name that doesn't sound so much like a function name. I'm thinking of `nrpnEventsEnabled` (which would default to `true`).

**Comment by misterinterrupt** [comment]
@djipco thanks for working with me on this! I have added a commit to reflect the changes suggested.

**Comment by djipco** [comment]
This looks awesome. Thank you so much for your work on this. I don't really have gear to test it with so I'll have to trust you that it does work as expected... ;-)

**Comment by djipco** [comment]
I just noticed something: the definition for the `nrpn` event in the jsdoc does not match the actual object. Do you think you can fix it?

**Comment by djipco** [comment]
The new `nrpn` event should also be linked in the documentation for the `addListener()` method.

**Comment by djipco** [comment]
Another small thing: the events usually have a reference to the object that triggered it in the `target` property. It would be better if the `nrpnEvent` also had that.

**Comment by misterinterrupt** [comment]
ok yeah, sounds good, I will make a PR for those things.

**Comment by djipco** [comment]
Awesome. Thank you again. 

Food for thought: it might be interesting to be able to listen to only  one type of NRPN events (`entry`, `increment` or `decrement`)...

**Comment by misterinterrupt** [comment]
the events maybe would be 'nrpn-entry', 'nrpn-increment', 'nrpn-decrement' for that scenario?

**Comment by djipco** [comment]
> the events maybe would be 'nrpn-entry', 'nrpn-increment', 'nrpn-decrement' for that scenario?

Yeah, that's what I was thinking. Would that be useful?

**Comment by misterinterrupt** [comment]
I will roll it around in the brain and come up with a thought for that :) 

Also, is there an integration test somewhere, like two webmidi instances that talk and receive messages?

**Comment by djipco** [comment]
> Also, is there an integration test somewhere, like two webmidi instances that talk and receive messages?

No, there is currently no such thing.

**Comment by misterinterrupt** [comment]
Here are some thoughts on the API design for events, thinking from the experience of developers who are building musical instruments using midi..

AFAIK, most NRPN uses would be 
a. using the 14-bit 'entry' value alone 
b. or the 'inc'/'dec' together
c. or using both those sets at once

The first two options(a,b) are useful for receiving data from controllers that only send either 'a' or 'b'. The MPD218 that I have only sends 'b'.
The last option, 'c', is what I have seen synths receiving e.g. in DSI synths, I believe the Tetra receives both depending on the parameter.

When looking at the webmidi implementation of NRPN as it is, the callback can take e.value by default, check if it is incremental, and return early in those cases.

```
function handleNRPN(e) {
  if(e.controller.type === 'increment') {
    myApp.channel[e.channel].synth.incrementMyValue(e.controller.number, e.value);
    return;
  }
  if(e.controller.type === 'decrement') {
    myApp.channel[e.channel].synth.decrementMyValue(e.controller.number, e.value);
    return;
  }
  myApp.channel[e.channel].synth.setValue(e.controller.number, e.value);
}
input.addListener('nrpn', "all", handleNRPN);
```
***In case it seems like the increment is a specific increment unit like 1, 10, 100, from what I have read, the value will be a single number like 0 or 1 for both increment and decrement messages, the value still passes through in case some controller does or someone wants to use it that way..

So otherwise it could be like 
```
function handleEntryNRPN(e) {
  myApp.channel[e.channel].synth.setMyValue(e.controller.number, e.value);
}
function handleIncrementNRPN(e) {
  myApp.channel[e.channel].synth.incrementMyValue(e.controller.number, e.value);
}
function handleDecrementNRPN(e) {
  myApp.channel[e.channel].synth.decrementMyValue(e.controller.number, e.value);
}
input.addListener('nrpn-entry', "all", handleEntryNRPN);
input.addListener('nrpn-increment', "all", handleIncrementNRPN);
input.addListener('nrpn-decrement', "all", handleDecrementNRPN);
```
or as simple as
```
input.addListener('nrpn-entry', "all", mySynth.setMyValue);
input.addListener('nrpn-increment', "all", mySynth.incrementMyValue);
input.addListener('nrpn-decrement', "all", mySynth.decrementMyValue);
```
But in all these scenarios, is it likely that one would make a 'decrementMyValue' function instead of read, increment, set all at once? 
```
function handleNRPN(e) {
  var oldValue = myApp.channel[e.channel].synth.getMyValue(e.controller.number);
  if(e.controller.type === 'increment') {
    myApp.channel[e.channel].synth.setMyValue(oldValue + 1, e.value);
    return;
  }
  if(e.controller.type === 'decrement') {
    myApp.channel[e.channel].synth.setMyValue(oldValue - 1, e.value);
    return;
  }
  myApp.channel[e.channel].synth.setMyValue(e.value);
}
input.addListener('nrpn', "all", handleNRPN);
```
and then with individual callbacks
```
function handleEntryNRPN(e) {
  var newValue = myApp.channel[e.channel].synth.getMyValue(e.controller.number);
  myApp.channel[e.channel].synth.setMyValue(newValue + 1, e.value);
}
function handleIncrementNRPN(e) {
  var newValue = myApp.channel[e.channel].synth.getMyValue(e.controller.number);
  myApp.channel[e.channel].synth.setMyValue(newValue - 1, e.value);
}
function handleDecrementNRPN(e) {
  var newValue = myApp.channel[e.channel].synth.getMyValue(e.controller.number);
  myApp.channel[e.channel].synth.setMyValue(newValue - 1, e.value);
}
input.addListener('nrpn-entry', "all", handleEntryNRPN);
input.addListener('nrpn-increment', "all", handleIncrementNRPN);
input.addListener('nrpn-decrement', "all", handleDecrementNRPN);
```
Inside each of those *MyValue functions would be some kind of routing by control number to change the actual values and I don't see that being repeated in each handler and perhaps it would even just be in that first handler, checking for type and getting the value and then switching through the available synth(or whatever) parameters indexed by control number and then changing that value.

 - - - 
In the context of developer implementation of web software using webmidi, afaict, it seems like a more in depth project would perhaps handle midi in one place and check for a number of properties on the events to route the control where it goes. Lighter projects may just opt for the individual handlers, which is convenient and less verbose. 
In any case, I feel that if one is going to use the NRPNs, listening on the three different types sort of makes extra handler functions that may be very similar, and at the most I would break it into the two types 'a' and 'b' above. The individual listeners are convenient for avoiding writing that if else or switch statement in the handler, so it really helps for getting quick progress.

Perhaps you see an alternative way to express these ideas, I'm just thinking it is likely that catch-all listeners and then beyond that, a dev would want control of their routing.. what does your experience tell you? Maybe other people will weigh in in time and we can adapt to other feedback as well. 
`</Ramble>`

**Comment by djipco** [comment]
Thanks a lot for your input on this. As I stated earlier, I do not have much experience using NRPNs so I welcome any feedback. In fact, I would trust your judgement on this more than my mine, given my limited experience.

For version 3 of WebMidi.js, I have been thinking about this idea of being able to add filters when adding listeners (via an additional `filters` object parameter). This would allow one to listen to only certain notes, or specific CC messages, etc. Perhaps this could apply to NRPNs as well...

**Comment by misterinterrupt** [comment]
I love that idea, it seems like a good way to simplify the midi receiving

**Pull request merged**
